apiVersion: v1
kind: Pod
metadata:
  name: postgres
  namespace: openfaas-fn # IMPORTANT : Même namespace que les fonctions pour simplifier
  labels:
    app: postgres
spec:
  containers:
    - name: postgres
      image: postgres:13
      env:
        - name: POSTGRES_PASSWORD
          value: "monSuperMotDePasse"
        - name: POSTGRES_DB
          value: "cofrap_db"
      ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: openfaas-fn
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
